//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Resources;
using System.Globalization;
namespace unitechRFIDSampleMAUI.Resources
{
    public class AppStrings
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;
        internal AppStrings() { }
        public static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new ResourceManager("unitechRFIDSampleMAUI.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        public static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        // Device Information Strings
        public static string DeviceName { get { return ResourceManager.GetString("DeviceName", resourceCulture); } }
        public static string SKU { get { return ResourceManager.GetString("SKU", resourceCulture); } }
        public static string Region { get { return ResourceManager.GetString("Region", resourceCulture); } }
        public static string Version { get { return ResourceManager.GetString("Version", resourceCulture); } }
        public static string RfidModule { get { return ResourceManager.GetString("RfidModule", resourceCulture); } }
        public static string RfidModuleVersion { get { return ResourceManager.GetString("RfidModuleVersion", resourceCulture); } }
        public static string EngineModule { get { return ResourceManager.GetString("EngineModule", resourceCulture); } }
        public static string EngineModuleVersion { get { return ResourceManager.GetString("EngineModuleVersion", resourceCulture); } }
        public static string SerialNumber { get { return ResourceManager.GetString("SerialNumber", resourceCulture); } }
        public static string Time { get { return ResourceManager.GetString("Time", resourceCulture); } }
        public static string Beep { get { return ResourceManager.GetString("Beep", resourceCulture); } }
        public static string ReadMode { get { return ResourceManager.GetString("ReadMode", resourceCulture); } }
        public static string Vibrator { get { return ResourceManager.GetString("Vibrator", resourceCulture); } }
        public static string Power { get { return ResourceManager.GetString("Power", resourceCulture); } }

        // RFID Configuration Parameters
        public static string ContinuousMode { get { return ResourceManager.GetString("ContinuousMode", resourceCulture); } }
        public static string InventoryTime { get { return ResourceManager.GetString("InventoryTime", resourceCulture); } }
        public static string IdleTime { get { return ResourceManager.GetString("IdleTime", resourceCulture); } }
        public static string Algorithm { get { return ResourceManager.GetString("Algorithm", resourceCulture); } }
        public static string StartQ { get { return ResourceManager.GetString("StartQ", resourceCulture); } }
        public static string MaxQ { get { return ResourceManager.GetString("MaxQ", resourceCulture); } }
        public static string MinQ { get { return ResourceManager.GetString("MinQ", resourceCulture); } }
        public static string Target { get { return ResourceManager.GetString("Target", resourceCulture); } }
        public static string Session { get { return ResourceManager.GetString("Session", resourceCulture); } }
        public static string SelectMode { get { return ResourceManager.GetString("SelectMode", resourceCulture); } }
        public static string Encoding { get { return ResourceManager.GetString("Encoding", resourceCulture); } }
        public static string Tari { get { return ResourceManager.GetString("Tari", resourceCulture); } }
        public static string BLF { get { return ResourceManager.GetString("BLF", resourceCulture); } }
        public static string ToggleTarget { get { return ResourceManager.GetString("ToggleTarget", resourceCulture); } }
        public static string FastMode { get { return ResourceManager.GetString("FastMode", resourceCulture); } }
        public static string DwellTime { get { return ResourceManager.GetString("DwellTime", resourceCulture); } }
        public static string RfMode { get { return ResourceManager.GetString("RfMode", resourceCulture); } }
        public static string LBT { get { return ResourceManager.GetString("LBT", resourceCulture); } }
        public static string FastId { get { return ResourceManager.GetString("FastId", resourceCulture); } }
        public static string TagFocus { get { return ResourceManager.GetString("TagFocus", resourceCulture); } }
        public static string PowerSavingMode { get { return ResourceManager.GetString("PowerSavingMode", resourceCulture); } }
        public static string LbtRssi { get { return ResourceManager.GetString("LbtRssi", resourceCulture); } }
        public static string AntennaSwitchingMode { get { return ResourceManager.GetString("AntennaSwitchingMode", resourceCulture); } }
        public static string FrequencySwitchingMode { get { return ResourceManager.GetString("FrequencySwitchingMode", resourceCulture); } }
        public static string Profile { get { return ResourceManager.GetString("Profile", resourceCulture); } }
        public static string AutoOffTime { get { return ResourceManager.GetString("AutoOffTime", resourceCulture); } }
        public static string AutoScreenOffTime { get { return ResourceManager.GetString("AutoScreenOffTime", resourceCulture); } }

        // UI Actions
        public static string Inventory { get { return ResourceManager.GetString("Inventory", resourceCulture); } }
        public static string CustomInventory { get { return ResourceManager.GetString("CustomInventory", resourceCulture); } }
        public static string Stop { get { return ResourceManager.GetString("Stop", resourceCulture); } }
        public static string Read { get { return ResourceManager.GetString("Read", resourceCulture); } }
        public static string Write { get { return ResourceManager.GetString("Write", resourceCulture); } }
        public static string Lock { get { return ResourceManager.GetString("Lock", resourceCulture); } }
        public static string Unlock { get { return ResourceManager.GetString("Unlock", resourceCulture); } }
        public static string FindTag { get { return ResourceManager.GetString("FindTag", resourceCulture); } }
        public static string Info { get { return ResourceManager.GetString("Info", resourceCulture); } }
        public static string Settings { get { return ResourceManager.GetString("Settings", resourceCulture); } }
        public static string NoSGTIN { get { return ResourceManager.GetString("NoSGTIN", resourceCulture); } }
        public static string Success { get { return ResourceManager.GetString("Success", resourceCulture); } }
        public static string Send { get { return ResourceManager.GetString("Send", resourceCulture); } }

        // Button and Device Names
        public static string RP902 { get { return ResourceManager.GetString("RP902", resourceCulture); } }
        public static string HT730 { get { return ResourceManager.GetString("HT730", resourceCulture); } }
        public static string RG768 { get { return ResourceManager.GetString("RG768", resourceCulture); } }
        public static string PA768E { get { return ResourceManager.GetString("PA768E", resourceCulture); } }
        public static string RP300 { get { return ResourceManager.GetString("RP300", resourceCulture); } }
        public static string RP300USB { get { return ResourceManager.GetString("RP300USB", resourceCulture); } }
        public static string EA530 { get { return ResourceManager.GetString("EA530", resourceCulture); } }
    }
}
